# Generated by Django 5.2 on 2025-04-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('pizza', 'Pizza'), ('coffee', 'Coffee'), ('burger', 'Burger'), ('dessert', 'Dessert'), ('beverage', 'Beverage')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
