# Generated by Django 5.2 on 2025-04-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_item_price_alter_item_category_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('coffee', 'Coffee'), ('burger', 'Burger'), ('dessert', 'Dessert'), ('beverage', 'Beverage')], default='pizza', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
