# Generated by Django 5.2 on 2025-04-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_item_category_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('coffee', 'Coffee'), ('burger', 'Burger'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('sandwich', 'Sandwich'), ('pasta', 'Pasta'), ('drink', 'Drink')], default='pizza', max_length=20),
        ),
    ]
